server:
  port: 80

#spring.h2.console.enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpleblog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 

#  datasource:
#    url: jdbc:h2:file:~/blog
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
  resources: # Static resources
    cache:
      period: 0

  # spring boot
  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false

  level:
    org.hibernate.type.descriptor.sql: trace

logging:
  level:
    org:
      springframework:
        security: DEBUG